### ISSUE TITLE
read failure

### ISSUE THREAD

**Issue by cokll** [DerekRies/arkpy#21]
Traceback (most recent call last):
  File "D:\arkprofile.py", line 5, in <module>
    profile = ArkProfile(file_path)
  File "build\bdist.win32\egg\arkpy\ark.py", line 329, in __init__
  File "build\bdist.win32\egg\arkpy\arktypes.py", line 28, in load_struct
  File "build\bdist.win32\egg\arkpy\arktypes.py", line 659, in __init__
  File "build\bdist.win32\egg\arkpy\arktypes.py", line 120, in load_and_set_next_property
  File "build\bdist.win32\egg\arkpy\arktypes.py", line 39, in load_property
  File "build\bdist.win32\egg\arkpy\arktypes.py", line 28, in load_struct
  File "build\bdist.win32\egg\arkpy\arktypes.py", line 740, in __init__
  File "build\bdist.win32\egg\arkpy\arktypes.py", line 120, in load_and_set_next_property
  File "build\bdist.win32\egg\arkpy\arktypes.py", line 41, in load_property
  File "build\bdist.win32\egg\arkpy\arktypes.py", line 219, in __init__
  File "build\bdist.win32\egg\arkpy\binary.py", line 63, in readNullTerminatedString
  File "build\bdist.win32\egg\arkpy\binary.py", line 194, in unpack
  File "build\bdist.win32\egg\arkpy\binary.py", line 22, in readBytes OverflowError: Python int too large to convert to C long

**Comment by cokll** [comment]
[root@localhost arkpy-master]# python example.py   
Traceback (most recent call last):
  File "example.py", line 62, in <module>
    main()
  File "example.py", line 55, in main
    load_arkprofile()
  File "example.py", line 17, in load_arkprofile
    profile = ArkProfile(fp)
  File "/root/arkpy-master/arkpy/ark.py", line 329, in __init__
    struct = arktypes.load_struct(stream)
  File "/root/arkpy-master/arkpy/arktypes.py", line 28, in load_struct
    struct = STRUCTS.get(name, BaseStruct)(stream=stream)
  File "/root/arkpy-master/arkpy/arktypes.py", line 659, in __init__
    self.load_and_set_next_property(stream)
  File "/root/arkpy-master/arkpy/arktypes.py", line 120, in load_and_set_next_property
    name, prop_type, value = load_property(stream)
  File "/root/arkpy-master/arkpy/arktypes.py", line 39, in load_property
    return (name, prop_type, load_struct(stream))
  File "/root/arkpy-master/arkpy/arktypes.py", line 28, in load_struct
    struct = STRUCTS.get(name, BaseStruct)(stream=stream)
  File "/root/arkpy-master/arkpy/arktypes.py", line 740, in __init__
    self.load_and_set_next_property(stream)
  File "/root/arkpy-master/arkpy/arktypes.py", line 120, in load_and_set_next_property
    name, prop_type, value = load_property(stream)
  File "/root/arkpy-master/arkpy/arktypes.py", line 41, in load_property
    return (name, prop_type, PROPERTIES[prop_type](stream=stream))
  File "/root/arkpy-master/arkpy/arktypes.py", line 219, in __init__
    self.value = stream.readNullTerminatedString()
  File "/root/arkpy-master/arkpy/binary.py", line 63, in readNullTerminatedString
    s = self.unpack(str(length - 1) + 's', length - 1)
  File "/root/arkpy-master/arkpy/binary.py", line 194, in unpack
    return unpack(fmt, self.readBytes(length))[0]
  File "/root/arkpy-master/arkpy/binary.py", line 22, in readBytes
    return self.base_stream.read(length)
MemoryError
