### ISSUE TITLE
Profile read error

### ISSUE THREAD

**Issue by Dragost** [DerekRies/arkpy#22]
Arkpy was working fine, but now arkpy give me back some profiles empty.
`{'Steam_Name': u'', 'Steam_ID': '00000000000000000', 'Character_Name': u''}`

Could it be due to the last update?
Can you help me?

Thank you very much.

**Comment by DerekRies** [comment]
It's possible a recent update has changed some of the file format structure. It's also possible that the update corrupted some data. You said this was only some profiles?

Is there anyway you can include the files themselves and I can take a look at it. I haven't kept up with any of the ark updates over the past year, so I'm not positive if they've changed anything substantive.

**Comment by Dragost** [comment]
Thanks for the quick reply.
I think that only the profiles of people, who have played in the last days, come empty.

I've uploaded 2 profiles. One of each. Here -> [https://we.tl/7NZ0Me12Vc](https://we.tl/7NZ0Me12Vc)
Thank you very much again

**Comment by apertaoxis** [comment]
`Traceback (most recent call last):
  File "profile.py", line 43, in <module>
    main()
  File "profile.py", line 11, in main
    profile = ark.ArkProfile(file_path)
  File "/usr/local/lib/python2.7/dist-packages/arkpy/ark.py", line 339, in __init__
    "PlayerLocalData.arkprofile files unsupported")
arkpy.ark.WrongFileType: PlayerLocalData.arkprofile files unsupported`

**Using:** file_path = 'STEAMIDXXXXXXXX.arkprofile'
Can you help me?

Thank you very much.

**Comment by DerekRies** [comment]
@apertaoxis This library only supports Version 1 of the Ark file formats. Since it was written there's probably been several version changes. That error is thrown when the file header information contains a different version number.
