### ISSUE TITLE
Issue installing / running 

### ISSUE THREAD

**Issue by uhaop** [DerekRies/arkpy#29]
not sure where else to post this so adding this any assistance is greatly appreciated thank you! 

I’m wanting to open arktribe files from ASA which is probably the reason it’s not working but this one of the errors I keep getting before it even loads the file.

Should I be running this in python 2?
 Is that possible ? Sorry I’m new at this !

(venv) G:\Downloads\arkpy-master\arkpy-master>python example2.py
Traceback (most recent call last):
  File "G:\Downloads\arkpy-master\arkpy-master\example2.py", line 1, in <module>
    from arkpy import ark, utils
  File "G:\Downloads\arkpy-master\arkpy-master\arkpy\ark.py", line 8, in <module>
    import arktypes
ModuleNotFoundError: No module named 'arktypes'

(venv) G:\Downloads\arkpy-master\arkpy-master>pip install arktypes
ERROR: Could not find a version that satisfies the requirement arktypes (from versions: none)
ERROR: No matching distribution found for arktypes

**Comment by cutec-chris** [comment]
@uhaop have you found an solution ? i would like to have the same
